FROM python:3.11-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /app
RUN uv venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN uv pip install --no-cache fastapi "uvicorn[standard]" docker pyyaml
COPY . .
EXPOSE 8502
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8502"]
